Module3/bestshopever/ads/urls.py
from django.views.generic import TemplateView

from . import views

from django.urls import path, re_path

app_name = 'ads'

urlpatterns = [
    re_path(r'^$', views.IndexView.as_view(), name='index'),
    path('categories/', views.Categories.as_view(), name='categories'),
    path('ads/recent/', views.AdList.as_view(), name='recent_ads'),
    path('ads/create/', views.AdCreate.as_view(), name='ad_create'),
    path('ads/<int:ad_id>/delete/', views.AdDelete.as_view(), name='ad_delete'),
    path('ads/<int:ad_id>/ad-delete-success/', TemplateView.as_view(template_name='ads/ad_delete_success.html'), name='ad-delete-success'),
    path('ads/<int:ad_id>/edit/', views.AdEdit.as_view(), name='ad_edit'),
    path('ads/<int:ad_id>/rate/', views.rate_ad_author, name='rate_ad_author'),
    re_path(r'^ads/(?P<ad_id>\w+)$', views.AdDetailed.as_view(), name='ad_show'),
    re_path(r'^cat-(?P<category_id>\w+)$', views.CategoryDetailed.as_view(), name='category_show'),
]

Module3/bestshopever/bestshopever/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('ads.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Module3/bestshopever/core/urls.py
from django.urls import path, re_path, reverse
from django.views.generic import TemplateView

from . import views
from .models import CustomUser

app_name = 'core'

urlpatterns = [
    path('login/', views.LoginView.as_view(template_name='core/login.html'), name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('signup/', views.SignUpView.as_view(), name="signup"),
    path('password_reset/', views.PasswordResetView.as_view(), name="password_reset"),
    path('password_reset_<int:user_id>/', views.PasswordResetValidateView.as_view(), name="password_reset_validate"),
    path('password_reset_completed/', TemplateView.as_view(template_name='core/password_reset_complete.html'),
         name="password_reset_completed"),
    path('user-<int:user_id>/', views.ProfileView.as_view(), name="profile"),
    path('user-<int:user_id>/edit/', views.ProfileEditView.as_view(), name="profile_edit"),
    path('user-<int:profile_id>/rate/', views.rate_user, name='rate_user'),
]

Module3/bestshopever/ads/models.py
from django.db import models

from core.models import CustomUser


def ad_image_path(instance, filename):
    user_id = instance.id
    return f'user_photos/user-{user_id}/{filename}'


class Category(models.Model):
    title = models.CharField(max_length=150, blank=False, default='Common')
    description = models.TextField(max_length=5000, blank=False, default='Uncategorized goods category')

    class Meta:
        verbose_name_plural = 'Categories'

    @classmethod
    def get_default_pk(cls):
        default_category, created = cls.objects.get_or_create(
            title='Common',
        )
        return default_category.pk

    def __str__(self):
        return f"{self.title}"

STATUS_CHOICES = [
    ('d', 'Draft'),
    ('p', 'Published'),
    ('w', 'Withdrawn'),
]


class Advertisement(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='ads')
    title = models.CharField(max_length=150, blank=False)
    description = models.TextField(max_length=5000, blank=False)
    image = models.ImageField(upload_to=ad_image_path, default='default.png')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='d')
    date_pub = models.DateTimeField(auto_now_add=True)
    date_edit = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.SET_DEFAULT, related_name='advertisements', default=Category.get_default_pk)

    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

    def __str__(self):
        return f"Ad \"{self.title}\""


class Comment(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='comments')
    ad = models.ForeignKey(Advertisement, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField(max_length=200)
    date_pub = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Comment from {} to ad #{}".format(self.author, self.ad.id)

Module3/bestshopever/ads/forms.py
from django import forms

from .models import Advertisement, Comment


class AdCreateForm(forms.ModelForm):

    class Meta:
        model = Advertisement
        fields = ['title', 'description', 'image', 'category', 'status']
        labels = {
            'title': 'Title',
            'description': 'Description of advertisement',
            'image': 'Product photo',
            'category': 'Choose category',
        }
        widgets = {
            'description': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Describe your product in detail'
                }
            ),
            'image': forms.ClearableFileInput(
                attrs={
                    'class': 'form-control',
                }
            )
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'placeholder': "Write your comment here"})
        }

Module3/bestshopever/ads/views.py
import time

from django.contrib.auth.decorators import login_required
from django.forms import forms
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from django.urls import reverse
from django.utils import timezone
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

from . import models
from .forms import AdCreateForm, CommentForm
from .models import Advertisement, Category, Comment
from core.models import Rating


class IndexView(ListView):
    model = Advertisement
    template_name = 'ads/index.html'
    context_object_name = 'ads'
    queryset = Advertisement.objects.order_by('-date_pub')[:4]


class AdList(ListView):
    model = Advertisement
    template_name = 'ads/ad_list.html'
    context_object_name = 'ads'
    queryset = Advertisement.objects.order_by('-date_pub')
    paginate_by = 12

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['is_listed'] = True
    #     return context


class Categories(ListView):
    model = Category
    template_name = 'ads/categories.html'
    context_object_name = 'categories'


class CategoryDetailed(DetailView):
    model = Category
    template_name = 'ads/category_show.html'
    context_object_name = 'category'
    pk_url_kwarg = 'category_id'


class AdDetailed(DetailView):
    model = Advertisement
    comment_form = CommentForm
    template_name = 'ads/ad_show.html'
    context_object_name = 'ad'
    pk_url_kwarg = 'ad_id'

    def get(self, request, ad_id, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context['comments'] = Comment.objects.filter(ad__pk=ad_id).order_by('-date_pub')[:5]
        context['comment_form'] = self.comment_form
        return self.render_to_response(context)

    def post(self, request, ad_id, *args, **kwargs):
        self.object = self.get_object()
        form = self.comment_form(request.POST)
        if not request.user.is_authenticated:
            form.add_error(None, forms.ValidationError('Please log in to leave a comment'))
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.ad = self.object
            comment.save()

        context = self.get_context_data(object=self.object)
        context.update({
            'comments': Comment.objects.filter(ad__pk=ad_id).order_by('-date_pub')[:5],
            'comment_form': form,
        })
        return self.render_to_response(context)


class AdCreate(CreateView):
    form_class = AdCreateForm
    template_name = 'ads/ad_create.html'

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            raise Exception('You are not allowed to create advertisement! Please sign in or sign up on previous page.')
        return super().get(request, *args, **kwargs)


    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        context = {}
        if form.is_valid():
            ad = form.save(commit=False)
            ad.author = request.user
            ad.date_pub = timezone.now()
            ad.save()
            context['form'] = self.form_class
            return redirect(reverse('ads:ad_show', kwargs={'ad_id': ad.id}))
        else:
            context['form'] = self.form_class
            return render(request, self.template_name, context)


class AdEdit(UpdateView):
    model = Advertisement
    template_name = 'ads/ad_edit.html'
    pk_url_kwarg = 'ad_id'
    form_class = AdCreateForm
    context_object_name = 'ad'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != self.request.user:
            raise Exception('You are not allowed to edit! Go away!')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        ad_id = self.kwargs['ad_id']
        return reverse('ads:ad_show', args=(ad_id, ))


class AdDelete(DeleteView):
    model = Advertisement
    template_name = 'ads/ad_delete.html'
    pk_url_kwarg = 'ad_id'
    context_object_name = 'ad'

    def get_success_url(self):
        ad_id = self.kwargs['ad_id']
        return reverse('ads:ad-delete-success', args=(ad_id, ))


def rate_ad_author(request, ad_id):
    ad = get_object_or_404(models.Advertisement, pk=ad_id)
    if request.user and request.user.is_authenticated:
        author_rating, created = Rating.objects.get_or_create(user_who_rate=request.user, user_rated=ad.author)
        author_rating.rating_value = request.POST.get('selected_rating')
        author_rating.save()
    print(request)
    return redirect(request.META.get('HTTP_REFERER'), request)

Module3/bestshopever/ads/templates/ads/ad_create.html
{% extends 'ads/base.html' %}

{% block title %}
    Create new ad
{% endblock title %}

{% block content %}
    <form action="{% url 'ads:ad_create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="OK">
    </form>
{% endblock content %}

Module3/bestshopever/ads/templates/ads/ad_delete.html
{% extends 'ads/base.html' %}

{% block title %}
    Ad delete
{% endblock title %}

{% block content %}
    {% if ad.author != user %}
        <h1>You cannot delete advertisement!</h1>
        <p>{{user}}</p>
        <p>{{ad.author}}f</p>
    {% else %}
        <h1>Are you sure to delete advertisement?</h1>
        <form method="post" action="{% url 'ads:ad_delete' ad.id %}">
            {% csrf_token %}
            <button type="submit">Yep, delete!</button>
            <a href="{% url 'ads:ad_show' ad.id %}">Oh, no!</a>
        </form>
    {% endif %}
{% endblock content %}

Module3/bestshopever/ads/templates/ads/ad_delete_success.html
{% extends 'ads/base.html' %}

{% block title %}
    Delete succeeded
{% endblock title %}

{% block content %}
    <h1>DELETION WAS SUCCESFUL!</h1>
    <h2>Feel yourself as a great destroyer!</h2>
    <a href="{% url 'ads:index' %}">На главную</a>
{% endblock content %}

Module3/bestshopever/ads/templates/ads/ad_list.html
{% extends 'ads/base.html' %}

{% block title %}
    Advertisements
{% endblock title %}

{% block content %}
    <section class="wrapper">
        <h1>Advertisements</h1>
        <p>Newest on top</p>
        {% include 'ads/ad_ul.html' %}
    </section>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock content %}

Module3/bestshopever/ads/templates/ads/ad_show.html
{% extends 'ads/base.html' %}

{% block title %}
    Advertisement "{{ ad.title }}"
{% endblock title %}

{% block content %}
    <section class="advertisement">
        <div class="advertisement__upper">
            <img src="{{ ad.image_url }}" alt="{{ ad.title }}" class="advertisement__image margined10">
            <div class="advertisement__summary">
                <p>{{ ad.category.title }}</p>
                <p class="advertisement__title">{{ ad.title }}</p>
                <p class="advertisement__published">published at {{ ad.date_pub.date }} by {{ ad.author }}</p>
            </div>
        </div>
        <p class="advertisement__description">{{ ad.description }}</p>
        {% if ad.author == user %}
            <a href="{% url 'ads:ad_edit' ad.pk %}" class="button">Edit advertisement</a>
        {% endif %}
        <p class="advertisement__author-rating">Author rating: {{ ad.author.rating_calc }}</p>
        {% with goto="ads:rate_ad_author" var=ad.id %}
            {% include 'core/rate_author.html' %}
        {% endwith %}

        {% if comments %}
            <h2>Comments:</h2>
            {% for comment in comments %}
                <p>{{ comment.author }}</p>
                <p>{{ comment.date_pub }}</p>
                <p>{{ comment.text }}</p>
            {% endfor %}
            {% else %}
            <h2>No comments yet. Be first!</h2>
        {% endif %}
        {% if ad.author != user %}
        <form method="post">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <button type="submit">Add comment</button>
        </form>
        {% endif %}
    </section>
{% endblock content %}

Module3/bestshopever/ads/templates/ads/ad_ul.html
{% if ads %}
<ul class="ads-list">
    {% for ad in ads %}
    {% if ad.status == 'p' %}
    <li class="ads-list__item">
        <div href="{% url 'ads:ad_show' ad.id %}" class="ads-list__card">
            <img class="ads-list__image" alt="{{ ad.title }}" src="{{ ad.image_url }}">
            <a href="{% url 'ads:ad_show' ad.id %}" class="ads-list__title">{{ ad.title }}</a>
            <p class="ads-list__description"> {{ ad.description|truncatechars:140 }}</p>
            <a href="{% url 'ads:category_show' ad.category.id %}" class="margined10">Category: {{ ad.category.title }}</a>
            <p class="ads-list__author">Author: {{ ad.author.username }} </p>
        </div>
    </li>
    {% endif %}
    {% endfor %}
</ul>
{% endif %}

Module3/bestshopever/ads/templates/ads/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'ads/css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
    <title>
        {% block title %}
            Best shop ever
        {% endblock title %}
    </title>
</head>
<body>
{% block page %}
    {% block header %}
        {% include 'ads/header.html' %}
    {% endblock header %}

    {% block content %}
    {% endblock content %}

    {% block footer %}
        {% include 'ads/footer.html' %}
    {% endblock footer %}
{% endblock page %}
</body>
{% include 'ads/ext_scripts.html' %}
</html>

Module3/bestshopever/ads/templates/ads/categories.html
{% extends 'ads/base.html' %}

{% block title %}
    Categories
{% endblock title %}

{% block content %}
    <section class="categories">
        {% if categories %}
        <ul class="categories__list">
            {% for cat in categories %}
            <li class="categories__item">
                <a href="{% url 'ads:category_show' cat.id %}" class="categories__title">{{ cat.title }}</a>
                <p> {{ cat.description }}</p>
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    </section>
{% endblock content %}

Module3/bestshopever/ads/templates/ads/category_show.html
{% extends 'ads/base.html' %}

{% block title %}
    {{ category.title }}
{% endblock title %}

{% block content %}
    <h1>{{ category.title }}</h1>
    {% with ads=category.advertisements.all %}
        {% include 'ads/ad_ul.html' %}
    {% endwith %}
{% endblock content %}

Module3/bestshopever/ads/templates/ads/ext_scripts.html
{% load static %}
<script type="text/javascript" src="{% static 'ads/js/lodash.js' %}"></script>
<script type="text/javascript" src="{% static 'ads/js/tween_max.js' %}"></script>
<script type="text/javascript" src="{% static 'ads/js/script.js' %}"></script>

Module3/bestshopever/ads/templates/ads/footer.html
<footer class="footer">
    <div class="wrapper">
            <p class="footer__credentials">Powered by Django and hard work of Vlad  aka LemanRus</p>
    </div>
</footer>

Module3/bestshopever/ads/templates/ads/header.html
<header class="wrapper header">
    <nav class="header__navigation">
        <ul class="header__menu">
        <li class="header__menu-item">
            <a href="{% url 'ads:recent_ads' %}">Advertisements</a>
        </li>
        <li class="header__menu-item">
            <a href="{% url 'ads:categories' %}">Categories</a>
        </li>
    </ul>
    </nav>
    <a class="header__logo" href={% url 'ads:index' %} data-text="Best shop ever">Best shop ever</a>
    <nav class="header__navigation">
    {% if user.is_authenticated %}
        <ul class="header__menu">
            <li class="header__menu-item">
                <a href="{% url 'core:profile' user.id %}">My profile</a>
            </li>
            <li class="header__menu-item">
                <a href="{% url 'core:logout' %}">Exit</a>
            </li>
        </ul>
    {% else %}
        <ul class="header__menu">
            <li class="header__menu-item">
                <a href="{% url 'core:signup' %}">Sign up</a>
            </li>
            <li class="header__menu-item">
                <a href="{% url 'core:login' %}">Sign in</a>
            </li>
        </ul>
    {% endif %}
    </nav>
</header>

Module3/bestshopever/ads/templates/ads/index.html
{% extends 'ads/base.html' %}

{% load static %}

{% block title %}
    Home
{% endblock title %}

{% block content %}
    <section class="wrapper index">
        <h1 class="hidden-text">Best shop ever</h1>
        <div class="index__greet">
            <div class="index__greet-text">
                <p>Greetings visitor!</p>
                <p>Behold the greatest bulletin board since the Aztec civilization! By reading this, you receive the great power of the knowledge of the universe.</p>
            </div>
            <img src="{% static 'ads/media/img.png' %}" class="index__image">
        </div>
        {% if ads %}
            <p>Ads fresh as the sea breeze:</p>
        {% endif %}
        {% include 'ads/ad_ul.html' %}
    </section>
{% endblock content %}

Module3/bestshopever/ads/templates/ads/recent_ads.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Advertisements</title>
</head>
<body>
<h1>Advertisements</h1>
<p>Newest on top</p>
{% if ads %}
<ul>
    {% for ad in ads %}
    <li>
        <a href="{% url 'ads:ad_show' ad.id %}">{{ ad }}</a>
        <p>{{ ad.author }}</p>
        <p>{{ ad.description }}</p>
    </li>
    {% endfor %}
</ul>
{% endif %}
</body>
</html>