Module3/bestshopever/ads/urls.py
from django.views.generic import TemplateView

from . import views

from django.urls import path, re_path

app_name = 'ads'

urlpatterns = [
    re_path(r'^$', views.IndexView.as_view(), name='index'),
    path('categories/', views.Categories.as_view(), name='categories'),
    path('ads/recent/', views.AdList.as_view(), name='recent_ads'),
    path('ads/create/', views.AdCreate.as_view(), name='ad_create'),
    path('ads/<int:ad_id>/delete/', views.AdDelete.as_view(), name='ad_delete'),
    path('ads/<int:ad_id>/ad-delete-success/', TemplateView.as_view(template_name='ads/ad_delete_success.html'), name='ad-delete-success'),
    path('ads/<int:ad_id>/edit/', views.AdEdit.as_view(), name='ad_edit'),
    path('ads/<int:ad_id>/rate/', views.rate_ad_author, name='rate_ad_author'),
    re_path(r'^ads/(?P<ad_id>\w+)$', views.AdDetailed.as_view(), name='ad_show'),
    re_path(r'^cat-(?P<category_id>\w+)$', views.CategoryDetailed.as_view(), name='category_show'),
]

Module3/bestshopever/bestshopever/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('ads.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Module3/bestshopever/core/urls.py
from django.urls import path, re_path, reverse
from django.views.generic import TemplateView

from . import views
from .models import CustomUser

app_name = 'core'

urlpatterns = [
    path('login/', views.LoginView.as_view(template_name='core/login.html'), name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('signup/', views.SignUpView.as_view(), name="signup"),
    path('password_reset/', views.PasswordResetView.as_view(), name="password_reset"),
    path('password_reset_<int:user_id>/', views.PasswordResetValidateView.as_view(), name="password_reset_validate"),
    path('password_reset_completed/', TemplateView.as_view(template_name='core/password_reset_complete.html'),
         name="password_reset_completed"),
    path('user-<int:user_id>/', views.ProfileView.as_view(), name="profile"),
    path('user-<int:user_id>/edit/', views.ProfileEditView.as_view(), name="profile_edit"),
    path('user-<int:profile_id>/rate/', views.rate_user, name='rate_user'),
]

Module3/bestshopever/core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from phone_field import PhoneField

from core.validators import validate_birth_date


def user_profile_photo_path(instance, filename):
    user_id = instance.id
    return f'user_photos/user-{user_id}/{filename}'


class CustomUser(AbstractUser):
    birth_date = models.DateField(blank=True, null=True, validators=[validate_birth_date,])
    photo = models.ImageField(upload_to=user_profile_photo_path, default='default.png')
    telephone = PhoneField(blank=True)
    email = models.EmailField("email address", blank=False)
    secret_question = models.CharField(blank=False, max_length=150, default='Name of your first pet')
    secret_answer = models.CharField(blank=False, max_length=50)

    def __str__(self):
        return f"{self.username}"

    def get_absolute_url(self):
        return reverse('core:profile', kwargs={'user_id': self.pk})

    @property
    def rating_calc(self):
        rating = Rating.objects.filter(user_rated=self).aggregate(calculated_rating=models.Avg('rating_value')).get('calculated_rating')
        if rating:
            return rating
        else:
            return 0


class Stars(models.IntegerChoices):
    ONE = 1, 'One'
    TWO = 2, 'Two'
    THREE = 3, 'Three'
    FOUR = 4, 'Four'
    FIVE = 5, 'Five'


class Rating(models.Model):
    user_who_rate = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='rate')
    user_rated = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='rated')
    rating_value = models.IntegerField(default=Stars.FIVE, choices=Stars.choices)

    def __str__(self):
        return f'User {self.user_who_rate} rated user \"{self.user_rated}\" with {self.rating_value} stars'

Module3/bestshopever/core/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.password_validation import validate_password
from django.utils.datetime_safe import datetime

from .models import CustomUser


class UserActions:
    birth_date = forms.DateField(label='Birth date', input_formats=['%d-%m-%Y'],
                                 widget=forms.SelectDateWidget(
                                     years=range(datetime.now().year - 70, datetime.now().year + 1), attrs={
                                         'class': 'form-control',
                                         'placeholder': 'dd-mm-yyyy',
                                     }))

    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if not email:
            raise forms.ValidationError('Enter email!')
        if email and CustomUser.objects.filter(email=email).exists() and CustomUser.objects.get_or_create(username=username)[1] == True:
            raise forms.ValidationError('Email entered is not free')
        return email


class SignupForm(UserCreationForm, UserActions):

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'birth_date', 'photo', 'telephone', 'secret_question', 'secret_answer')
        widgets = {
            'birth_date': forms.TextInput(attrs={'placeholder': 'YYYY-MM-DD'}),
        }


class PasswordResetValidateForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, validators=[validate_password])

    class Meta:
        model = CustomUser
        fields = ('secret_answer', 'password')
        labels = {
            'secret_answer': 'Answer',
            'password': 'Enter your new password',
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email:
            raise forms.ValidationError('Enter email!')
        if email and not CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError('Email doesn\'t exist. Please sign up')
        return email


class UpdateProfileForm(forms.ModelForm):

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email',
                  'birth_date', 'photo', 'telephone'
                  ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['birth_date'].widget.years = range(datetime.now().year - 70, datetime.now().year + 1)

Module3/bestshopever/core/views.py
from django.contrib import messages
from django.contrib.auth import logout, login
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404
from django.contrib.auth.views import LoginView
from django.urls import reverse
from django.views import View
from django.views.generic import DetailView, UpdateView

from .models import CustomUser, Rating
from .forms import SignupForm, PasswordResetValidateForm


# Create your views here.


def logout_view(request):
    logout(request)
    return redirect(reverse("ads:index"))

def rate_user(request, profile_id):
    profile = get_object_or_404(CustomUser, pk=profile_id)
    if request.user and request.user.is_authenticated:
        profile_rating, created = Rating.objects.get_or_create(user_who_rate=request.user, user_rated=profile)
        profile_rating.rating_value = request.POST.get('selected_rating')
        profile_rating.save()
    return redirect(request.META.get('HTTP_REFERER'), request)


class SignUpView(View):
    template_name = 'core/signup.html'
    form = SignupForm

    def get(self, request, *args, **kwargs):
        context = {
            'form': self.form,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(reverse('core:profile', kwargs={'user_id': user.id}))
        else:
            return render(request, self.template_name, {
                'form': form,
            })


class ProfileView(DetailView):
    model = CustomUser
    template_name = 'core/profile.html'
    pk_url_kwarg = 'user_id'
    context_object_name = 'profile'


class ProfileEditView(UpdateView):
    model = CustomUser
    template_name = 'core/edit_profile.html'
    pk_url_kwarg = 'user_id'
    context_object_name = 'profile'
    form_class = SignupForm

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj != request.user:
            raise Http404('You are not allowed to edit profile that is not yours')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        obj = self.get_object()
        login(self.request, obj)
        messages.success(self.request, "Profile updated succesfully")
        return reverse("core:profile", kwargs={"user_id": obj.id})


class PasswordResetView(View):
    template_name = 'core/password_reset.html'
    context = {
        'error': "",
    }

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        email_for_reset = request.POST.get('email_for_reset')
        if email_for_reset and not CustomUser.objects.filter(email=email_for_reset).exists():
            self.context['error'] = 'Email does not exist. Check it or sign up.'
            return render(request, self.template_name, self.context)
        else:
            user = CustomUser.objects.filter(email=email_for_reset).get()
            return redirect(reverse('core:password_reset_validate',  kwargs={'user_id': user.id}))


class PasswordResetValidateView(View):
    template_name = 'core/password_reset_validate.html'
    form = PasswordResetValidateForm

    def get(self, request, *args, **kwargs):
        context = {
            'form': self.form,
            'secret_question': CustomUser.objects.get(pk=kwargs['user_id']).secret_question,
            'user_id': kwargs['user_id'],
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST)
        user_who_reset = CustomUser.objects.get(pk=kwargs['user_id'])
        if form.data.get('secret_answer') != user_who_reset.secret_answer:
            form.add_error('secret_answer', 'Secret answer is not correct')
        if form.is_valid():
            print(user_who_reset)
            user_who_reset.set_password(form.cleaned_data.get('password'))
            user_who_reset.save()
            return redirect(reverse('core:password_reset_completed'))
        else:
            return render(request, self.template_name, {
                'form': form,
                'secret_question': user_who_reset.secret_question,
                'user_id': kwargs['user_id'],
            })

Module3/bestshopever/core/templates/core/edit_profile.html
{% extends 'ads/base.html' %}

{% block title %}
    Edit {{ profile }}
{% endblock title %}

{% block content %}
    <h1>Editing: {{profile}}</h1>
    <img src="{{profile.avatar.url}}" alt="avatar">

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save changes</button>
    </form>
{% endblock content %}

Module3/bestshopever/core/templates/core/login.html
{% extends 'ads/base.html' %}

{% block title %}
    Sign up
{% endblock title %}

{% block content %}
    <H1>Greetings!</H1>
    <form method="post" action="{% url 'core:login' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Log in</button>
    </form>
    <a href="{% url 'core:password_reset' %}">Forgot your password?</a>
{% endblock content %}

Module3/bestshopever/core/templates/core/password_reset.html
{% extends 'ads/base.html' %}

{% block title %}
    Reset password
{% endblock title %}

{% block content %}
    <form method="post" action="{% url 'core:password_reset' %}">
        {% csrf_token %}
        {% if error %}
        <ul>
            <li><p>{{ error }}</p></li>
            <li><a href="{% url 'core:signup' %}">Sign up</a></li>
        </ul>
        {% endif %}
        <label for="email_for_reset">Your email</label>
        <input type="text" id="email_for_reset" name="email_for_reset">
        <button type="submit">Go ahead</button>
    </form>
    <a href="{% url 'ads:index' %}">Home</a>
{% endblock content %}

Module3/bestshopever/core/templates/core/password_reset_complete.html
{% extends 'ads/base.html' %}

{% block title %}
    Password reset completed
{% endblock title %}

{% block content %}
    <h1>Password reset completed succesfully!</h1>
    <p>You can now login with new password</p>
    <a href="{% url 'core:login' %}">Log in</a>
    <a href="{% url 'ads:index' %}">Home</a>
{% endblock content %}

Module3/bestshopever/core/templates/core/password_reset_validate.html
{% extends 'ads/base.html' %}

{% block title %}
    Password reset validation
{% endblock title %}

{% block content %}
    <h1>Answer the secret question</h1>
    <h2>{{ secret_question }}:</h2>
    <form method="post" action="{% url 'core:password_reset_validate' user_id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
{% endblock content %}

Module3/bestshopever/core/templates/core/profile.html
{% extends 'ads/base.html' %}

{% block title %}
    {{ profile }}
{% endblock title %}

{% block content %}
    <section class="profile">
     {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </li>
    {% endfor %}
        <div class="profile__upper">
            <h1>Info about {{profile}}</h1>
            {% if user.id == profile.id %}
                <a href="{% url 'core:profile_edit' profile.id %}" class="button">Edit profile</a>
                <a href="{% url 'ads:ad_create' %}" class="button">Create advertisement</a>
            {% endif %}
        </div>
        <div class="profile__page">
        {% if profile.photo %}
            <img src="{{ profile.photo.url }}" alt="photo" class="profile__photo">
        {% endif %}
            <div class="profile__credentials">
                <p>Name: {{profile.first_name}} {{ profile.last_name }}</p>
                <p>E-mail: {{profile.email}}</p>
                <p>Telephone: {{profile.telephone}}</p>
                <p>Birthday: {{profile.birth_date|date:"d F Y"}}</p>
            </div>
        </div>
        <h2>My ads:</h2>
        <ul class="profile__ads-list">
            {% for ad in profile.ads.all %}
                <li class="profile__ads-item">
                    <a href="{% url 'ads:ad_show' ad.id %}">{{ ad }}</a>
                    <img src="{{ ad.image_url }}">
                </li>
            {% endfor %}
        </ul>
        <p>Author rating: {{ profile.rating_calc }}</p>
        {{ error }}
        {% if user.id != profile.id %}
            {{ error }}
            {% with goto="core:rate_user" var=profile.id %}
                {% include 'core/rate_author.html' %}
            {% endwith %}
        {% endif %}
    </section>
{% endblock content %}

Module3/bestshopever/core/templates/core/rate_author.html
{% if ad.author != user %}
    <form method="post" action="{% url goto var %}">
        {% csrf_token %}
        <select name="selected_rating" class="selected_rating">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
        </select>
        <button type="submit">Rate author</button>
    </form>
{% endif %}

Module3/bestshopever/core/templates/core/signup.html
{% extends 'ads/base.html' %}

{% block title %}
    Sign up
{% endblock title %}

{% block content %}
    <H1>New user</H1>
    {% if not user.is_authenticated %}
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Sign up!</button>
        </form>
    {% else %}
        <H2>You have been already registered!</H2>
    {% endif %}
{% endblock content %}